name-template: "IDDEFIX v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 New Features"
    labels: ["feature", "enhancement"]
    commit-keywords: ["feat", "feature"]
  - title: "🐛 Bugfixes"
    labels: ["fix", "bug"]
    commit-keywords: ["fix"]
  - title: "💗 Other Tag Highlights"
    labels: ["example", "docs", "style", "test", "build"]
    commit-keywords: ["docs", "build", "style", "refactor"]

change-template: "- {title} (@{author})"
change-title-escapes: "true"

template: |
  # IDDEFIX v$NEXT_PATCH_VERSION
  *Coming soon!*

  ## 🚀 New Features
  $CHANGES

  ## 💗 Other Tag Highlights
  $CHANGES

  ## 🐛 Bugfixes
  $CHANGES

  ## 👋👩‍💻 Contributors
  $CONTRIBUTORS

  ## 📝Full changelog
  [`git log $PREVIOUS_TAG...$CURRENT_TAG`](https://github.com/OWNER/REPO/compare/$PREVIOUS_TAG...$CURRENT_TAG)

include-commit-messages: true
sort-by: "merged_at"
sort-direction: descending

