name: Release Drafter (Manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the release (e.g., v0.1.0)'
        required: false
      publish:
        description: 'Publish release (true) or just draft (false)?'
        required: false
        default: 'false'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ github.event.inputs.version }}
          publish: ${{ github.event.inputs.publish }}
